### ISSUE TITLE
set up & test Twitter & LinkedIn integration

### ISSUE THREAD

**Issue by nowviskie** [clirdlf/jobeleon-dlf#14]
maybe Facebook too... 

Not certain we'll use these at all -- we don't want them to feel too automatic/formulaic since we offer "friendly, customized" promotion -- but worth experimenting with. LinkedIn could probably especially be set to auto-post, since it's all about the jobs. (Otherwise workflow for DLF staff may just be to create a custom tweet using the poster's provided handle whenever we approve a job. We have never posted jobs to Facebook before, and may not want to at all.)

**Comment by waynegraham** [comment]
The apps for Twitter and Facebook have been created. If you decide to auto-tweet new jobs (it's currently not enabled), we'll need to make sure the template is working properly.

**Comment by waynegraham** [comment]
I updated the authorized SDK domains in the LinkedIn developers. I have no idea how to test this though...

**Comment by waynegraham** [comment]
Wait, just read the docs on this. This integration is to allow people to **apply** for jobs with their LinkedIn profile. It does not apparently **post** to LinkedIn.

**Comment by waynegraham** [comment]
Ok, so there's a bunch of different documentation which is kind of vague. I revoked the OAuth key and re-authenticated. Now under **Post As** there are two options. I selected DLF. Maybe now new jobs will be posted?

**Comment by nowviskie** [comment]
Looks like it worked! https://www.linkedin.com/company/digital-library-federation/

**Comment by bquon** [comment]
Yay! Fantastic. Thank you Wayne.

**Comment by waynegraham** [comment]
Is this one closable yet?

**Comment by bquon** [comment]
It looks like these stopped posting as 'Updates' to our company page almost as soon as we got it up and running last year; https://www.linkedin.com/company/digital-library-federation/ 

Can we see about getting new job posts synced again?

**Comment by waynegraham** [comment]
This isn't a theme issue so I'm closing it. However, I deployed an update to the plugin and theme and followed up in other channels.
