### ISSUE TITLE
Invoice Issues: "100% discount applied"+ missing payment form

### ISSUE THREAD

**Issue by bquon** [clirdlf/jobeleon-dlf#24]
Every listing has a "Payment URL" link that can be provided to users to send them straight to the page where they can pay. Each of those URLs links to a payment page that currently say "100% discount applied", without users needing to entering a code. 

![screen shot 2017-12-06 at 12 54 14 pm](https://user-images.githubusercontent.com/24256562/33676825-c90dd1a0-da84-11e7-8d21-a5f54f78f6cd.png)

See live example: https://jobs.diglib.org/wpjobboard/payment/pay/?payment_hash=46-df68cadb5ca38dfa9716cb131031e91320f05fd7

How do we edit these invoice pages to remove this option, which may mislead folks to think they don't need to pay?

**Comment by waynegraham** [comment]
This is an error in the WPJobBoard Plugin. I edited `application/libraries/Module/Api/Payment.php` and added `.wpjb-none { display:none; }` to the template and alerted the developer of the issue. 

Hopefully the patch I sent gets rolled in to the next release. If it does not, this will pop up again when the plugin gets updated.
