### ISSUE TITLE
Editing listing type

### ISSUE THREAD

**Issue by bquon** [clirdlf/jobeleon-dlf#25]
It would be 💕 ✨ 🌈 🦄  and save a lot of back and forth if administrators could switch a job type from member (free) to non-member (paid) **after** the the listing has been submitted. Is that possible?

**Comment by waynegraham** [comment]
Are you wanting WordPress administrators (e.g. you) to be able to do this? Like in the admin console? 

Or are you talking about some sort of mechanism for people who administer their jobs to change this?

**Comment by waynegraham** [comment]
I'm going to close this as it's actually a question for the plugin author. This was sent 2/9.
