### ISSUE TITLE
Editing job descriptions

### ISSUE THREAD

**Issue by bquon** [clirdlf/jobeleon-dlf#27]
Description boxes on individual listings appear blank, and cannot be seen/edited, even though content appears on published pages. This only seems to be an issue on the admin side, not on the employer interface. Confirmed this issue in multiple browsers, and with Aliya, who is having the same problem! 

**image showing blank description box**
![screen shot 2018-03-05 at 9 59 44 am](https://user-images.githubusercontent.com/24256562/36982530-10c065d4-205e-11e8-8719-ef91c70616ab.png)
**image showing content on the same (published) page**
![screen shot 2018-03-05 at 9 59 59 am](https://user-images.githubusercontent.com/24256562/36982531-10d36652-205e-11e8-81d2-ae34f88f4ae5.png)

**Comment by waynegraham** [comment]
Three was a plugin causing a JavaScript error; this should be fixed now.
