### ISSUE TITLE
Random assignment of company + employer profiles 

### ISSUE THREAD

**Issue by bquon** [clirdlf/jobeleon-dlf#29]
Report received today:

> I was just posting a job at the jobs.diglib.org site for the University of North Carolina at Chapel Hill Libraries, and after logging in, I noticed that some information was being auto-filled for the University of Miami.
>I was able to change that in my posting, but when I click on the profile for UNC-Chapel Hill, it still defaults to this profile page for the University of Miami: https://jobs.diglib.org/company/university-of-miami-2/.

It looks like a few recent submissions have had a random Employer assigned to them. (example: a [Yale listing with CDL listed as the employer](https://jobs.diglib.org/wp-admin/admin.php?page=wpjb-job&action=edit&id=446))

And some Employer/Company profiles don't match up either. (example: a [UNC profile linked to Employer Chuck Henry](https://jobs.diglib.org/wp-admin/admin.php?page=wpjb-employers&action=edit&id=35))

It's only happening to some of the listings. Others have the correct institution associated.

**Comment by waynegraham** [comment]
I've submitted a ticket to the plugin author for a permanent fix. In the mean time, the workaround will have to be changing the employer in the admin interface.
