### ISSUE TITLE
Paypal Sync Error: "Receiver Email Is Invalid"

### ISSUE THREAD

**Issue by bquon** [clirdlf/jobeleon-dlf#30]
Every paid order that's submitted shows a status of 'Failed' and a log message 'receiver email is invalid [SIVY@CLIR.ORG]'. However, payments for each have been accepted via Paypal and show up in our account. 

See the log of activities at the bottom of this page as example: [https://jobs.diglib.org/wp-admin/admin.php?page=wpjb-payment&action=edit&id=106], + screenshot of the same issue below:

![screen shot 2019-01-29 at 2 45 48 pm](https://user-images.githubusercontent.com/24256562/51936825-12b05e80-23d7-11e9-8ef4-5417fc93c4fe.png)

I've been checking Paypal, then changing the status to 'completed' for each order and marking each job as 'paid' before approving.

edit: sivy@clir.org IS still working for Paypal login and the password hasn't changed since before this issue appeared.

**Comment by waynegraham** [comment]
This isn't a theme issue, so I'm closing this (but will take it up).
