### ISSUE TITLE
Update "About DLF Jobs" in Footer

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/jobeleon-dlf#32]
Update supplied text in the footer for the "About DLF Jobs"

https://github.com/clirdlf/jobeleon-dlf/blob/master/footer.php#L66-L68

**Comment by LouisaKwasigroch** [comment]
I've updated the text here: https://docs.google.com/document/d/10Ehm3AabDfn_noSt0W1Jl3NIK5HzANFMKvTRA7DjFB0/edit#

Ready.
